# SPDX-FileCopyrightText: 2025 Kaleb A. Ascevich
# SPDX-License-Identifier: AGPL-3.0-or-later

excluded:
  - .build
  - .swiftpm

disabled_rules:
  - attribute_name_spacing
  - closing_brace
  - closure_parameter_position
  - colon
  - comma
  - comment_spacing
  - file_length
  - function_name_whitespace
  - identifier_name
  - line_length
  - no_space_in_method_call
  - opening_brace
  - return_arrow_whitespace
  - statement_position
  - switch_case_alignment
  - trailing_comma
  - trailing_newline
  - trailing_semicolon
  - trailing_whitespace
  - todo
  - vertical_parameter_alignment
  - vertical_parameter_alignment_on_call
  - vertical_whitespace

opt_in_rules:
  - array_init
  - comma_inheritance
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
#  - convenience_type
  - direct_return
  - discouraged_assert
  - discouraged_none_name
  - discouraged_optional_boolean
  - discouraged_optional_collection
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - explicit_init
#  - extension_access_modifier
  - fatal_error_message
  - file_header
  - file_name_no_space
  - first_where
  - flatmap_over_map_reduce
  - identical_operands
  - implicit_return
  - implicitly_unwrapped_optional
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - local_doc_comment
  - lower_acl_than_parent
  - missing_docs
  - modifier_order
  - non_overridable_class_declaration
  - nslocalizedstring_key
  - optional_enum_case_matching
  - override_in_extension
#  - pattern_matching_keywords
  - prefer_key_path
  - prefer_self_in_static_references
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - reduce_into
  - redundant_nil_coalescing
  - redundant_self_in_closure
  - redundant_type_annotation
  - return_value_from_void_function
  - self_binding
  - shorthand_argument
  - shorthand_optional_binding
  - sorted_first_last
  - toggle_bool
  - trailing_closure
  - unavailable_function
  - unhandled_throwing_task
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - untyped_error_in_catch
  - unused_parameter
  - weak_delegate

analyzer_rules:
  - capture_variable
  - typesafe_array_init
  - unused_declaration
  - unused_import

# There are times when one actually needs to use these for
# their intended purposes.
force_cast: warning
force_try: warning

nesting:
  type_level: 2

file_header:
  required_pattern: |
                    \/\/ SPDX-FileCopyrightText: \d{4} .+
                    \/\/ SPDX-License-Identifier: AGPL-3.0-or-later
